fix = true
line-length = 79
select = [
    "A",      # flake8-builtins
    "ANN",    # flake8-annotations
    "ASYNC",  # flake8-async
    "ARG",    # flake8-unused-arguments
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "C90",    # mccabe
    "DJ",     # flake8-django
    "E",      # pycodestyle
    "ERA",    # eradicate
    "F",      # Pyflakes
    "N",      # pep8-naming
    "PIE",    # flake8-pie
    "PL",     # Pylint
    "RET",    # flake8-return
    "RUF",    # RUF
    "S",      # flake8-bandit
    "T20",    # flake8-print
    "UP",     # pyupgrade
    "W"       # pycodestyle
]
ignore = ["ANN401", "PD", "NPY", "RUF012"]
show-fixes = true
target-version = "py311"

[per-file-ignores]
"*_tests.py" = ["ANN", "B", "S"]
"**/migrations/*.py" = ["E"]

[mccabe]
max-complexity = 4
